### PR TITLE
1.8.2 new features

### PR DESCRIPTION
**Pull request by RP-RISING-STAR**
+3 new features

1. Weekday abbreviation in transaction list.
2. Quick Search based on "Note" column filtering.
3. Budgets sorting (By date, name, amount).

screenshot_1528221235

### CODE REVIEW

**Comment by yetanothercoder** [comment]
Thanks for new features, one suggestion:

> Quick Search based on "Note" column filtering.

Would it be more useful to make "quick search" by all text transaction fields too: project, payee, category and note ?

**Comment by RP-RISING-STAR** [comment]
@yetanothercoder, technically it's possible. But I think for fields with limited number of options (projects, payee, category) the filter window is better. Because in this case you can select the account (or payee, category) you're interested in and search for transactions related to this category/account/payee. + Not sure what behavior should be in case, I filtered something in filter window, now I'm typing something in quick search. Should be the filter cleared once I type the first character?

**Comment by yetanothercoder** [comment]
well, logically - such quick-search should not conflict with other filters and works like specifying additional filters so:

> Not sure what behavior should be in case, I filtered something in filter window, now I'm typing something in quick search. Should be the filter cleared once I type the first character?

not cleared but just adding more conditions to sql query, e.g. user set project and/or dates in window filter and then he can narrow the results by setting the quick search to add filters by other fields: note or payee or category etc.
As I remember all similar "quick search" in other sites/apps works in such manner: "filtering by all" and many users would expect it working in this way.
BUT the main risk here - is performance as you'll have to add all joins to transaction table which can be critical for some devices and db size, so not sure how it'd be practical finally, just thoughts so far.

**Comment by dtruebin** [comment]
* × in the quick search should appear only after the first character is entered. It makes no sense until then and rather brings confusion: "will this button hide the search field or clear the text I haven't even entered yet?"
* Abbreviated weekdays in the transaction list is a very welcome addition.  
One small issue I see is that weekdays are not capitalized in Russian locale. They are placed in the beginning of line and I think it would look better if they were capitalized, e.g., "Вт" instead of "вт".

I wish each feature was added under a separate PR for easier discussion.

**Comment by RP-RISING-STAR** [comment]
@yetanothercoder, well I think I can try to implement the quick search the way you propose. I have pretty big database of my personal transactions (starting from 2014), so will see how it'll affect performance on my old OnePlus One.

@dtruebin, will add "x" button disappear for empty quick box. Regarding to capitalization of weekday abbreviation in Russian, I think this is a localization issue. There is no specific related to English or any other locale. But will try to implement some workaround on this.

@dtruebin, appreciate your help if you can tell me how to rebase my fork to dsolonenko:master. I rebased it with "git rebase upstream/master" command, but GitHub portal still says that my fork is 10+ commits ahead of dsolonenko: master.

**Pull request merged**
